title: aveyilagrun
email: az.nurgaliyeva@gmail.com
description: >- # ignore newlines until "baseurl:"
  Personal website.
baseurl: ""
url: "http://aveyilagrun.github.io"
github_username:  aveyilagrun
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache